/**
 * Command: epost-kit verify
 * Full pre-release/pre-init audit pipeline.
 * Runs lint + health checks + generates mermaid dependency graph.
 */

import { writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { existsSync, mkdirSync } from "node:fs";
import pc from "picocolors";
import { dirExists, fileExists } from "../core/file-system.js";
import { loadAllManifests } from "../core/package-resolver.js";
import {
  buildRefRegistry,
  validateReferences,
} from "../core/ref-validator.js";
import { runSkillHealthChecks } from "../core/skill-health-checks.js";
import { logger } from "../core/logger.js";

interface VerifyOptions {
  verbose?: boolean;
  yes?: boolean;
  strict?: boolean;
  dir?: string;
}

async function findPackagesDir(cwd: string): Promise<string | null> {
  const paths = [join(cwd, "packages"), join(cwd, "..", "packages")];
  for (const p of paths) {
    const resolved = resolve(p);
    if (
      (await dirExists(resolved)) &&
      (await fileExists(join(resolved, "core", "package.yaml")))
    ) {
      return resolved;
    }
  }
  return null;
}

// ─── Mermaid Graph Generator ───

function generateMermaidGraph(healthStats: {
  skillCount: number;
  connectionCount: { extends: number; requires: number; conflicts: number; enhances: number };
}, allConnections: Map<string, { extends: string[]; requires: string[]; conflicts: string[]; enhances: string[] }>): string {
  const lines: string[] = [
    "# Skill Dependency Graph",
    "",
    "> Auto-generated by `epost-kit verify`. Do not edit manually.",
    "",
    "```mermaid",
    "graph TD",
  ];

  // Add nodes and edges from connections
  for (const [skill, conn] of allConnections) {
    const safeId = skill.replace(/-/g, "_");

    for (const parent of conn.extends) {
      const parentId = parent.replace(/-/g, "_");
      lines.push(`  ${parentId}[${parent}] --> ${safeId}[${skill}]`);
    }

    for (const dep of conn.requires) {
      const depId = dep.replace(/-/g, "_");
      lines.push(`  ${depId}[${dep}] -.->|requires| ${safeId}[${skill}]`);
    }

    for (const target of conn.enhances) {
      const targetId = target.replace(/-/g, "_");
      lines.push(`  ${safeId}[${skill}] ~~~|enhances| ${targetId}[${target}]`);
    }

    for (const target of conn.conflicts) {
      const targetId = target.replace(/-/g, "_");
      lines.push(`  ${safeId}[${skill}] x--x|conflicts| ${targetId}[${target}]`);
    }
  }

  lines.push("```");
  lines.push("");

  // Stats summary
  const cc = healthStats.connectionCount;
  lines.push("## Stats");
  lines.push("");
  lines.push(`- **Skills**: ${healthStats.skillCount}`);
  lines.push(`- **Extends**: ${cc.extends}`);
  lines.push(`- **Requires**: ${cc.requires}`);
  lines.push(`- **Conflicts**: ${cc.conflicts}`);
  lines.push(`- **Enhances**: ${cc.enhances}`);
  lines.push("");

  return lines.join("\n");
}

// ─── Connection Extractor (reads from packages/) ───

async function extractAllConnections(
  packagesDir: string,
): Promise<Map<string, { extends: string[]; requires: string[]; conflicts: string[]; enhances: string[] }>> {
  const { readFile, readdir } = await import("node:fs/promises");
  const connections = new Map<string, { extends: string[]; requires: string[]; conflicts: string[]; enhances: string[] }>();

  async function findSkillFiles(dir: string): Promise<string[]> {
    const results: string[] = [];
    try {
      const entries = await readdir(dir, { withFileTypes: true });
      for (const entry of entries) {
        const fullPath = join(dir, entry.name);
        if (entry.isDirectory()) results.push(...(await findSkillFiles(fullPath)));
        else if (entry.name === "SKILL.md") results.push(fullPath);
      }
    } catch { /* skip */ }
    return results;
  }

  // Reuse the frontmatter parser approach from skill-health-checks
  function parseFm(content: string): { name?: string; extends?: string[]; requires?: string[]; conflicts?: string[]; enhances?: string[] } {
    const match = content.match(/^---\s*\n([\s\S]*?)\n---/);
    if (!match) return {};

    const metadata: Record<string, string | string[]> = {};
    let currentKey: string | null = null;

    for (const line of match[1].split("\n")) {
      const trimmed = line.trim();
      if (!trimmed) continue;
      if (trimmed.startsWith("-") && currentKey) {
        if (!Array.isArray(metadata[currentKey])) metadata[currentKey] = [];
        (metadata[currentKey] as string[]).push(trimmed.substring(1).trim());
        continue;
      }
      const ci = trimmed.indexOf(":");
      if (ci === -1) continue;
      const key = trimmed.substring(0, ci).trim();
      let value = trimmed.substring(ci + 1).trim();
      if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'")))
        value = value.substring(1, value.length - 1);
      if (value.startsWith("[") && value.endsWith("]")) {
        metadata[key] = value.substring(1, value.length - 1).split(",").map(i => i.trim().replace(/^["']|["']$/g, "")).filter(Boolean);
      } else if (value) {
        metadata[key] = value;
      } else {
        currentKey = key;
      }
    }

    const asArr = (v: string | string[] | undefined): string[] => Array.isArray(v) ? v : [];
    return {
      name: typeof metadata.name === "string" ? metadata.name : undefined,
      extends: asArr(metadata.extends),
      requires: asArr(metadata.requires),
      conflicts: asArr(metadata.conflicts),
      enhances: asArr(metadata.enhances),
    };
  }

  const files = await findSkillFiles(packagesDir);
  for (const f of files) {
    try {
      const content = await readFile(f, "utf-8");
      const fm = parseFm(content);
      if (!fm.name) continue;
      const hasAny = (fm.extends?.length ?? 0) + (fm.requires?.length ?? 0) + (fm.conflicts?.length ?? 0) + (fm.enhances?.length ?? 0) > 0;
      if (hasAny) {
        connections.set(fm.name, {
          extends: fm.extends ?? [],
          requires: fm.requires ?? [],
          conflicts: fm.conflicts ?? [],
          enhances: fm.enhances ?? [],
        });
      }
    } catch { /* skip */ }
  }

  return connections;
}

// ─── Main ───

export async function runVerify(opts: VerifyOptions): Promise<void> {
  const cwd = opts.dir ? resolve(opts.dir) : process.cwd();
  const claudeDir = join(cwd, ".claude");

  if (!(await dirExists(claudeDir))) {
    logger.error("No .claude/ directory found. Run epost-kit init first.");
    process.exit(1);
  }

  const packagesDir = await findPackagesDir(cwd);
  if (!packagesDir) {
    logger.error("Cannot find packages/ directory.");
    process.exit(1);
  }

  console.log(pc.bold("\nepost-kit verify\n"));

  // Load manifests
  const manifests = await loadAllManifests(packagesDir);
  const registry = buildRefRegistry(manifests);

  // Run all checks in parallel
  const [refErrors, healthResult, allConnections] = await Promise.all([
    validateReferences(claudeDir, registry),
    runSkillHealthChecks(packagesDir, claudeDir, manifests),
    extractAllConnections(packagesDir),
  ]);

  const { issues, stats } = healthResult;

  // ── Report ──
  const errors = issues.filter((i) => i.severity === "error");
  const warnings = issues.filter((i) => i.severity === "warn");
  const infos = issues.filter((i) => i.severity === "info");

  console.log(`  Refs:         ${refErrors.length === 0 ? pc.green("OK") : pc.red(`${refErrors.length} broken`)}`);
  console.log(`  Skills:       ${stats.skillCount} found`);
  console.log(`  Connections:  ${stats.connectionCount.extends}e ${stats.connectionCount.requires}r ${stats.connectionCount.conflicts}c ${stats.connectionCount.enhances}h`);
  console.log(`  Completeness: ${stats.completeness.withDescription}/${stats.skillCount} desc, ${stats.completeness.withKeywords}/${stats.skillCount} kw, ${stats.completeness.withPlatforms}/${stats.skillCount} plat`);
  console.log();

  if (errors.length > 0 || refErrors.length > 0) {
    console.log(pc.red(`  ${errors.length + refErrors.length} error(s) — blocking`));
    for (const e of errors) {
      console.log(`    ${pc.red("✗")} [${e.rule}] ${e.skill}: ${e.message}`);
    }
  }

  if (warnings.length > 0) {
    console.log(pc.yellow(`  ${warnings.length} warning(s)`));
  }

  if (infos.length > 0) {
    console.log(pc.dim(`  ${infos.length} info`));
  }

  // ── Generate mermaid graph ──
  const docsDir = join(cwd, "docs");
  if (!existsSync(docsDir)) mkdirSync(docsDir, { recursive: true });

  const graphContent = generateMermaidGraph(stats, allConnections);
  const graphPath = join(docsDir, "skill-dependency-graph.md");
  await writeFile(graphPath, graphContent, "utf-8");
  console.log(pc.dim(`\n  Graph: ${graphPath}`));

  // ── Exit ──
  const hasErrors = refErrors.length > 0 || errors.length > 0;
  const hasWarnings = warnings.length > 0;

  if (hasErrors) {
    console.log(pc.red("\n  FAIL — errors must be fixed before release/init\n"));
    process.exit(1);
  } else if (opts.strict && hasWarnings) {
    console.log(pc.yellow("\n  FAIL — strict mode: warnings treated as errors\n"));
    process.exit(1);
  } else {
    console.log(pc.green("\n  PASS\n"));
  }
}
